# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ventana1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

#importar las imagenes
import imagenes

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 552)
        Dialog.setMinimumSize(QtCore.QSize(800, 552))
        Dialog.setMaximumSize(QtCore.QSize(800, 552))
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":imagenes/logotipo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("*{\n"
"    font: 75 italic 14pt \"Times New Roman\";\n"
"    color: rgb(0, 0, 127);\n"
"}")
        self.fondo = QtWidgets.QLabel(Dialog)
        self.fondo.setGeometry(QtCore.QRect(0, 0, 800, 552))
        self.fondo.setMinimumSize(QtCore.QSize(800, 552))
        self.fondo.setMaximumSize(QtCore.QSize(800, 552))
        self.fondo.setText("")
        self.fondo.setPixmap(QtGui.QPixmap(":imagenes/pediatria.png"))
        self.fondo.setScaledContents(True)
        self.fondo.setObjectName("fondo")
        self.texto = QtWidgets.QLabel(Dialog)
        self.texto.setGeometry(QtCore.QRect(30, 480, 241, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.texto.setFont(font)
        self.texto.setObjectName("texto")
        self.barra1 = QtWidgets.QProgressBar(Dialog)
        self.barra1.setGeometry(QtCore.QRect(20, 510, 751, 31))
        self.barra1.setStyleSheet("QProgressBar{\n"
"    \n"
"    background-color: rgb(232, 232, 174);\n"
"    \n"
"    color: rgb(0, 170, 127);\n"
"    border-style:solid;\n"
"    border-radius:10px;\n"
"    text-align:center;\n"
"}\n"
"QProgressBar::chunk{\n"
"    border-radius:10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(136, 203, 223, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.barra1.setProperty("value", 0)
        self.barra1.setObjectName("barra1")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 310, 470, 100))
        self.label.setMinimumSize(QtCore.QSize(470, 100))
        self.label.setMaximumSize(QtCore.QSize(470, 100))
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Bienvenido"))
        self.texto.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#0000ff;\"/></p></body></html>"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">BIENVENIDO AL SISTEMA DE INFORMACIÓN</span></p><p align=\"center\"><span style=\" font-weight:600;\">DE HISTORIALES CLÍNICOS PEDIÁTRICOS</span></p><p align=\"center\"><span style=\" font-weight:600;\">&quot;CONSULTORIO PEDIÁTRICO DIVINO NIÑO JESÚS&quot;</span></p></body></html>"))
