# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ventana1_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
#importar imagenes
import imagenes

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(489, 338)
        Dialog.setMinimumSize(QtCore.QSize(489, 338))
        Dialog.setMaximumSize(QtCore.QSize(490, 338))
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":imagenes/logotipo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("font: 75 italic 10pt \"Times New Roman\";\n"
"color: rgb(0, 0, 127);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setMinimumSize(QtCore.QSize(490, 338))
        self.frame.setMaximumSize(QtCore.QSize(490, 338))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.barra1 = QtWidgets.QProgressBar(self.frame)
        self.barra1.setGeometry(QtCore.QRect(10, 300, 472, 30))
        self.barra1.setMinimumSize(QtCore.QSize(0, 30))
        self.barra1.setMaximumSize(QtCore.QSize(16777215, 30))
        self.barra1.setStyleSheet("QProgressBar{\n"
"    \n"
"    background-color: rgb(232, 232, 174);\n"
"    \n"
"    color: rgb(0, 170, 127);\n"
"    border-style:solid;\n"
"    border-radius:10px;\n"
"    text-align:center;\n"
"}\n"
"QProgressBar::chunk{\n"
"    border-radius:10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(136, 203, 223, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.barra1.setProperty("value", 24)
        self.barra1.setObjectName("barra1")
        self.texto = QtWidgets.QLabel(self.frame)
        self.texto.setGeometry(QtCore.QRect(10, 270, 250, 20))
        self.texto.setMinimumSize(QtCore.QSize(250, 20))
        self.texto.setMaximumSize(QtCore.QSize(250, 20))
        self.texto.setText("")
        self.texto.setObjectName("texto")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 160, 321, 91))
        self.label.setMinimumSize(QtCore.QSize(321, 91))
        self.label.setMaximumSize(QtCore.QSize(321, 91))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 491, 341))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":imagenes/pediatria.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.barra1.raise_()
        self.texto.raise_()
        self.label.raise_()
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Bienvenido"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">BIENVENIDO AL SISTEMA DE INFORMACIÓN</span></p><p align=\"center\"><span style=\" font-weight:600;\">DE HISTORIALES CLÍNICOS PEDIÁTRICOS</span></p><p align=\"center\"><span style=\" font-weight:600;\">&quot;CONSULTORIO PEDIÁTRICO DIVINO NIÑO JESÚS&quot;</span></p></body></html>"))

